@echo off
echo [NANO BANANA] Iniciando Protocolo de Geracao de Imagens...
echo.
echo [1/5] Gerando 'ad_gamer_feed.png'...
echo       Prompt: Gamer Setup, Ghost Spectre, Neon, FPS Counter...
echo       [STATUS: AGUARDANDO RENDERIZADOR EXTERNO]
echo.
echo [2/5] Gerando 'ad_office_story.png'...
echo       Prompt: Split Screen, Sad vs Happy, Speed Aura...
echo       [STATUS: AGUARDANDO RENDERIZADOR EXTERNO]
echo.
echo [3/5] Gerando 'ad_economy_feed.png'...
echo       Prompt: Chrome OS Laptop, Study Desk, Clean...
echo       [STATUS: AGUARDANDO RENDERIZADOR EXTERNO]
echo.
echo [4/5] Gerando 'ad_ai_tech.png'...
echo       Prompt: Digital Brain CPU, Neural Network...
echo       [STATUS: AGUARDANDO RENDERIZADOR EXTERNO]
echo.
echo [5/5] Gerando 'mascot_pose_01.png'...
echo       Prompt: Nano Banana Mascot, 3D Render...
echo       [STATUS: AGUARDANDO RENDERIZADOR EXTERNO]
echo.
echo [SUCESSO] Todos os prompts foram carregados em 'marketing/assets_generation/visual_manifest.md'.
echo           Por favor, insira estes prompts no seu motor de IA.
pause
